In [104]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv

In [105]:
%matplotlib inline

In [143]:
data = pd.read_excel('dummy.xlsx', header=None)

In [144]:
data = data.to_numpy()[1:]

In [142]:
data


array([[1, 10, 10, 10, 10],
       [2, 11, 11, 11, 11],
       [3, 12, 12, 12, 12],
       [4, 13, 13, 13, 13],
       [5, 14, 14, 14, 14],
       [6, 15, 15, 15, 15],
       [7, 16, 16, 16, 16],
       [8, 17, 17, 17, 17],
       [9, 18, 18, 18, 18],
       [10, 19, 19, 19, 19],
       [11, 20, 20, 20, 20],
       [12, 21, 21, 21, 21],
       [13, 22, 22, 22, 22],
       [14, 23, 23, 23, 23],
       [15, 24, 24, 24, 24],
       [16, 25, 25, 25, 25],
       [17, 26, 26, 26, 26],
       [18, 27, 27, 27, 27],
       [19, 28, 28, 28, 28],
       [20, 29, 29, 29, 29],
       [21, 30, 30, 30, 30],
       [22, 31, 31, 31, 31],
       [23, 32, 32, 32, 32],
       [24, 33, 33, 33, 33],
       [25, 34, 34, 34, 34],
       [26, 35, 35, 35, 35],
       [27, 36, 36, 36, 36],
       [28, 37, 37, 37, 37],
       [29, 38, 38, 38, 38],
       [30, 39, 39, 39, 39],
       [31, 40, 40, 40, 40],
       [32, 41, 41, 41, 41],
       [33, 42, 42, 42, 42],
       [34, 43, 43, 43, 43],
       [35, 44, 44, 44,

In [148]:
idx = 0
X, Y = [], []

while True:
    if idx+15 >= len(data):
        break
    X.append(data[idx:idx+15])
    Y.append(data[idx+1])
    idx += 1
    
    

In [152]:
Y

[array([2, 11, 11, 11, 11], dtype=object),
 array([3, 12, 12, 12, 12], dtype=object),
 array([4, 13, 13, 13, 13], dtype=object),
 array([5, 14, 14, 14, 14], dtype=object),
 array([6, 15, 15, 15, 15], dtype=object),
 array([7, 16, 16, 16, 16], dtype=object),
 array([8, 17, 17, 17, 17], dtype=object),
 array([9, 18, 18, 18, 18], dtype=object),
 array([10, 19, 19, 19, 19], dtype=object),
 array([11, 20, 20, 20, 20], dtype=object),
 array([12, 21, 21, 21, 21], dtype=object),
 array([13, 22, 22, 22, 22], dtype=object),
 array([14, 23, 23, 23, 23], dtype=object),
 array([15, 24, 24, 24, 24], dtype=object),
 array([16, 25, 25, 25, 25], dtype=object),
 array([17, 26, 26, 26, 26], dtype=object),
 array([18, 27, 27, 27, 27], dtype=object),
 array([19, 28, 28, 28, 28], dtype=object),
 array([20, 29, 29, 29, 29], dtype=object),
 array([21, 30, 30, 30, 30], dtype=object),
 array([22, 31, 31, 31, 31], dtype=object)]

In [109]:
print(x)

[[      0      1    2        3                  4
0  year  month  day  avg_tem  day_precipitation], [      0      1    2        3                  4
0  year  month  day  avg_tem  day_precipitation
1     1     10   10       10                 10],       0      1    2        3                  4
0  year  month  day  avg_tem  day_precipitation
1     1     10   10       10                 10
2     2     11   11       11                 11]


In [110]:
x=[[data.head(1)],[data.head(2)]]

In [111]:
print(data.head(2))

      0      1    2        3                  4
0  year  month  day  avg_tem  day_precipitation
1     1     10   10       10                 10


In [112]:
print(data.loc[[1,2,3,4],:])

   0   1   2   3   4
1  1  10  10  10  10
2  2  11  11  11  11
3  3  12  12  12  12
4  4  13  13  13  13


In [113]:
x=[data.loc[[1,2,3,4],:]]

In [114]:
print(x)

[   0   1   2   3   4
1  1  10  10  10  10
2  2  11  11  11  11
3  3  12  12  12  12
4  4  13  13  13  13]


In [122]:
x=[data.loc[[1],:]]
print(x)

[   0   1   2   3   4
1  1  10  10  10  10]


In [124]:
x[0]

0   1   2   3   4
1  1  10  10  10  10

In [95]:
x=data.loc[[0,1,2,3,4],:]
print(x)

      0      1    2        3                  4
0  year  month  day  avg_tem  day_precipitation
1     1     10   10       10                 10
2     2     11   11       11                 11
3     3     12   12       12                 12
4     4     13   13       13                 13


In [49]:
x=data.iloc[0:4,:]
print(x)

      0      1    2        3                  4
0  year  month  day  avg_tem  day_precipitation
1     1     10   10       10                 10
2     2     11   11       11                 11
3     3     12   12       12                 12


In [50]:
x=[data.iloc[2:4,:]]
print(x)

[   0   1   2   3   4
2  2  11  11  11  11
3  3  12  12  12  12]


In [51]:
a=[[1,2,3]]
b=[[4,5,6]]
a.append(b)
print(a)

[[1, 2, 3], [[4, 5, 6]]]


In [53]:
x=[data.iloc[2,:]]
x2=[data.iloc[3,:]]
x.append(x2)
print(x)

[0     2
1    11
2    11
3    11
4    11
Name: 2, dtype: object, [0     3
1    12
2    12
3    12
4    12
Name: 3, dtype: object]]


In [54]:
x=[[data.iloc[2,:]],[data.iloc[3,:]]]
print(x)

[[0     2
1    11
2    11
3    11
4    11
Name: 2, dtype: object], [0     3
1    12
2    12
3    12
4    12
Name: 3, dtype: object]]


In [55]:
x=[data.loc[[2,3,4],:]]
print(x)

[   0   1   2   3   4
2  2  11  11  11  11
3  3  12  12  12  12
4  4  13  13  13  13]


In [61]:
x=[data.loc[[14:16],:]]
print(x)

SyntaxError: invalid syntax (<ipython-input-61-11089c7bb74b>, line 1)

In [82]:
data = pd.read_excel('dummy.xlsx', header=None)

In [83]:
print(data)

       0      1    2        3                  4
0   year  month  day  avg_tem  day_precipitation
1      1     10   10       10                 10
2      2     11   11       11                 11
3      3     12   12       12                 12
4      4     13   13       13                 13
5      5     14   14       14                 14
6      6     15   15       15                 15
7      7     16   16       16                 16
8      8     17   17       17                 17
9      9     18   18       18                 18
10    10     19   19       19                 19
11    11     20   20       20                 20
12    12     21   21       21                 21
13    13     22   22       22                 22
14    14     23   23       23                 23
15    15     24   24       24                 24
16    16     25   25       25                 25
17    17     26   26       26                 26
18    18     27   27       27                 27
19    19     28   28

In [87]:
data = list(data)

In [88]:
print(data)

[0, 1, 2, 3, 4]


In [160]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv
%matplotlib inline
data = pd.read_excel('dummy.xlsx', header=None)

In [161]:
data = data.to_numpy()[1:]

In [162]:
data

array([[1, 10, 10, 10, 10],
       [2, 11, 11, 11, 11],
       [3, 12, 12, 12, 12],
       [4, 13, 13, 13, 13],
       [5, 14, 14, 14, 14],
       [6, 15, 15, 15, 15],
       [7, 16, 16, 16, 16],
       [8, 17, 17, 17, 17],
       [9, 18, 18, 18, 18],
       [10, 19, 19, 19, 19],
       [11, 20, 20, 20, 20],
       [12, 21, 21, 21, 21],
       [13, 22, 22, 22, 22],
       [14, 23, 23, 23, 23],
       [15, 24, 24, 24, 24],
       [16, 25, 25, 25, 25],
       [17, 26, 26, 26, 26],
       [18, 27, 27, 27, 27],
       [19, 28, 28, 28, 28],
       [20, 29, 29, 29, 29],
       [21, 30, 30, 30, 30],
       [22, 31, 31, 31, 31],
       [23, 32, 32, 32, 32],
       [24, 33, 33, 33, 33],
       [25, 34, 34, 34, 34],
       [26, 35, 35, 35, 35],
       [27, 36, 36, 36, 36],
       [28, 37, 37, 37, 37],
       [29, 38, 38, 38, 38],
       [30, 39, 39, 39, 39],
       [31, 40, 40, 40, 40],
       [32, 41, 41, 41, 41],
       [33, 42, 42, 42, 42],
       [34, 43, 43, 43, 43],
       [35, 44, 44, 44,

In [163]:
idx = 0
X,Y = [], []

In [164]:
while True:
    if idx+15 >= len(data):
        break
    X.append(data[idx:idx+15])
    Y.append(data[idx+15])
    idx += 1

In [165]:
X

[array([[1, 10, 10, 10, 10],
        [2, 11, 11, 11, 11],
        [3, 12, 12, 12, 12],
        [4, 13, 13, 13, 13],
        [5, 14, 14, 14, 14],
        [6, 15, 15, 15, 15],
        [7, 16, 16, 16, 16],
        [8, 17, 17, 17, 17],
        [9, 18, 18, 18, 18],
        [10, 19, 19, 19, 19],
        [11, 20, 20, 20, 20],
        [12, 21, 21, 21, 21],
        [13, 22, 22, 22, 22],
        [14, 23, 23, 23, 23],
        [15, 24, 24, 24, 24]], dtype=object),
 array([[2, 11, 11, 11, 11],
        [3, 12, 12, 12, 12],
        [4, 13, 13, 13, 13],
        [5, 14, 14, 14, 14],
        [6, 15, 15, 15, 15],
        [7, 16, 16, 16, 16],
        [8, 17, 17, 17, 17],
        [9, 18, 18, 18, 18],
        [10, 19, 19, 19, 19],
        [11, 20, 20, 20, 20],
        [12, 21, 21, 21, 21],
        [13, 22, 22, 22, 22],
        [14, 23, 23, 23, 23],
        [15, 24, 24, 24, 24],
        [16, 25, 25, 25, 25]], dtype=object),
 array([[3, 12, 12, 12, 12],
        [4, 13, 13, 13, 13],
        [5, 14, 14, 14, 14]

In [166]:
Y

[array([16, 25, 25, 25, 25], dtype=object),
 array([17, 26, 26, 26, 26], dtype=object),
 array([18, 27, 27, 27, 27], dtype=object),
 array([19, 28, 28, 28, 28], dtype=object),
 array([20, 29, 29, 29, 29], dtype=object),
 array([21, 30, 30, 30, 30], dtype=object),
 array([22, 31, 31, 31, 31], dtype=object),
 array([23, 32, 32, 32, 32], dtype=object),
 array([24, 33, 33, 33, 33], dtype=object),
 array([25, 34, 34, 34, 34], dtype=object),
 array([26, 35, 35, 35, 35], dtype=object),
 array([27, 36, 36, 36, 36], dtype=object),
 array([28, 37, 37, 37, 37], dtype=object),
 array([29, 38, 38, 38, 38], dtype=object),
 array([30, 39, 39, 39, 39], dtype=object),
 array([31, 40, 40, 40, 40], dtype=object),
 array([32, 41, 41, 41, 41], dtype=object),
 array([33, 42, 42, 42, 42], dtype=object),
 array([34, 43, 43, 43, 43], dtype=object),
 array([35, 44, 44, 44, 44], dtype=object),
 array([36, 45, 45, 45, 45], dtype=object)]

In [167]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv
%matplotlib inline
data = pd.read_excel('final_version.xlsx', header=None)
data = data.to_numpy()[1:]
data

idx = 0
X, Y = [], []

while True:
    if idx+15 >= len(data):
        break
    X.append(data[idx:idx+15])
    Y.append(data[idx+15])
    idx += 1

X

Y

[array([1960, 1, 16, -5, 0], dtype=object),
 array([1960, 1, 17, -5.3, 0], dtype=object),
 array([1960, 1, 18, -2.5, 0], dtype=object),
 array([1960, 1, 19, 2.1, 0], dtype=object),
 array([1960, 1, 20, -0.5, 0], dtype=object),
 array([1960, 1, 21, -6.1, 0], dtype=object),
 array([1960, 1, 22, -9.5, 0], dtype=object),
 array([1960, 1, 23, -13.1, 0], dtype=object),
 array([1960, 1, 24, -12.5, 0], dtype=object),
 array([1960, 1, 25, -7.3, 2.2], dtype=object),
 array([1960, 1, 26, -7.2, 0.1], dtype=object),
 array([1960, 1, 27, -10.5, 0.1], dtype=object),
 array([1960, 1, 28, -11, 0], dtype=object),
 array([1960, 1, 29, -7.5, 0], dtype=object),
 array([1960, 1, 30, -0.2, 0], dtype=object),
 array([1960, 1, 31, 2.6, 0], dtype=object),
 array([1960, 2, 1, 0.8, 0], dtype=object),
 array([1960, 2, 2, 1.2, 0], dtype=object),
 array([1960, 2, 3, 1.2, 0], dtype=object),
 array([1960, 2, 4, -1.2, 0], dtype=object),
 array([1960, 2, 5, 1.3, 0], dtype=object),
 array([1960, 2, 6, 6.7, 0], dtype=obje

In [168]:
X

[array([[1960, 1, 1, -1.6, 0],
        [1960, 1, 2, -1.9, 0.4],
        [1960, 1, 3, 4, 0],
        [1960, 1, 4, 7.5, 0],
        [1960, 1, 5, -4.6, 0],
        [1960, 1, 6, -5.2, 0],
        [1960, 1, 7, 1.3, 0.1],
        [1960, 1, 8, 1.9, 0],
        [1960, 1, 9, 2.3, 1.2],
        [1960, 1, 10, 2.2, 0.1],
        [1960, 1, 11, -2.3, 0],
        [1960, 1, 12, -3.8, 0],
        [1960, 1, 13, -2.8, 0],
        [1960, 1, 14, -1.5, 0.4],
        [1960, 1, 15, -4.8, 0]], dtype=object),
 array([[1960, 1, 2, -1.9, 0.4],
        [1960, 1, 3, 4, 0],
        [1960, 1, 4, 7.5, 0],
        [1960, 1, 5, -4.6, 0],
        [1960, 1, 6, -5.2, 0],
        [1960, 1, 7, 1.3, 0.1],
        [1960, 1, 8, 1.9, 0],
        [1960, 1, 9, 2.3, 1.2],
        [1960, 1, 10, 2.2, 0.1],
        [1960, 1, 11, -2.3, 0],
        [1960, 1, 12, -3.8, 0],
        [1960, 1, 13, -2.8, 0],
        [1960, 1, 14, -1.5, 0.4],
        [1960, 1, 15, -4.8, 0],
        [1960, 1, 16, -5, 0]], dtype=object),
 array([[1960, 1, 3, 4,

In [169]:
!pip -V

pip 20.1.1 from /Users/bagminseo/Desktop/coding/Python/keras/practice/test_env/lib/python3.7/site-packages/pip (python 3.7)


In [170]:
!pip install sklearn


  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1315 sha256=c289e01e06c65f82d16046f85eafe00f48aa25309e7fc7293e3cb65a9bfd8f5d
  Stored in directory: /Users/bagminseo/Library/Caches/pip/wheels/46/ef/c3/157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn


In [268]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [269]:
len(X_train)

17520

In [270]:
X_test


[array([[2009, 7, 29, 25.5, 0.1],
        [2009, 7, 30, 26.5, 0],
        [2009, 7, 31, 26.7, 0],
        [2009, 8, 1, 25.4, 21.5],
        [2009, 8, 2, 25.8, 1.5],
        [2009, 8, 3, 25.2, 0],
        [2009, 8, 4, 26.9, 0],
        [2009, 8, 5, 27.6, 0],
        [2009, 8, 6, 26.6, 0.5],
        [2009, 8, 7, 25.8, 0.5],
        [2009, 8, 8, 26.5, 0.5],
        [2009, 8, 9, 28.7, 0],
        [2009, 8, 10, 27.8, 0],
        [2009, 8, 11, 23.8, 113.5],
        [2009, 8, 12, 23.5, 80.5]], dtype=object),
 array([[1993, 5, 19, 18.3, 0],
        [1993, 5, 20, 21, 0],
        [1993, 5, 21, 18.3, 8.7],
        [1993, 5, 22, 19.1, 4.4],
        [1993, 5, 23, 19, 0],
        [1993, 5, 24, 19.6, 0],
        [1993, 5, 25, 15.7, 11.3],
        [1993, 5, 26, 17.8, 0],
        [1993, 5, 27, 20.4, 0],
        [1993, 5, 28, 21.5, 0],
        [1993, 5, 29, 24.5, 0],
        [1993, 5, 30, 23.3, 0],
        [1993, 5, 31, 24.4, 0],
        [1993, 6, 1, 24.7, 4.6],
        [1993, 6, 2, 16.1, 76.5]], dtype=

In [271]:
import keras

In [272]:
from keras.layers import Input, Dense, LSTM

In [273]:
from keras.models import Model

In [274]:
def build_model(input_shape):
    x = Input(shape=input_shape)

    h = LSTM(128, return_sequences=True, activation='tanh', kernel_initializer='he_normal')(x)
    h = LSTM(128, return_sequences=True, activation='tanh', kernel_initializer='he_normal')(h)
    h = LSTM(128, activation='tanh', kernel_initializer='he_normal')(h)

    y = Dense(1, activation='linear')(h)
    return Model(inputs=x, outputs=y)




In [275]:
model = build_model((15, 4))

In [276]:
model.summary()

Model: "model_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_12 (InputLayer)        (None, 15, 4)             0         
_________________________________________________________________
lstm_19 (LSTM)               (None, 15, 128)           68096     
_________________________________________________________________
lstm_20 (LSTM)               (None, 15, 128)           131584    
_________________________________________________________________
lstm_21 (LSTM)               (None, 128)               131584    
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 129       
Total params: 331,393
Trainable params: 331,393
Non-trainable params: 0
_________________________________________________________________


In [277]:
from keras.optimizers import Adam

In [278]:
model.compile(loss='mse', optimizer=Adam(), metrics=['acc', 'mae'])

In [279]:
Y_train = np.array(Y_train)[:, -1].reshape(-1, 1)

In [280]:
X_train = np.array(X_train)[:, :, 1:]

In [281]:
X_train.shape

(17520, 15, 4)

In [282]:
Y_train.shape


(17520, 1)

In [283]:
model.fit(X_train, Y_train, epochs=100)

Epoch 1/100
17520/17520 [==============================] - 19s 1ms/step - loss: 209.9842 - acc: 0.0787 - mae: 5.5911
Epoch 2/100
17520/17520 [==============================] - 19s 1ms/step - loss: 202.9431 - acc: 0.0918 - mae: 5.4744
Epoch 3/100
17520/17520 [==============================] - 20s 1ms/step - loss: 200.5287 - acc: 0.1180 - mae: 5.4067
Epoch 4/100
17520/17520 [==============================] - 19s 1ms/step - loss: 198.4679 - acc: 0.1305 - mae: 5.4086
Epoch 5/100
17520/17520 [==============================] - 20s 1ms/step - loss: 196.2657 - acc: 0.1497 - mae: 5.3650
Epoch 6/100
17520/17520 [==============================] - 21s 1ms/step - loss: 193.8669 - acc: 0.1472 - mae: 5.3329
Epoch 7/100
17520/17520 [==============================] - 20s 1ms/step - loss: 191.9346 - acc: 0.1465 - mae: 5.2810
Epoch 8/100
17520/17520 [==============================] - 21s 1ms/step - loss: 188.5277 - acc: 0.1577 - mae: 5.2360
Epoch 9/100
17520/17520 [==============================] - 21s 1

17520/17520 [==============================] - 23s 1ms/step - loss: 26.9873 - acc: 0.2365 - mae: 2.4320
Epoch 71/100
17520/17520 [==============================] - 23s 1ms/step - loss: 20.4185 - acc: 0.2549 - mae: 2.2017
Epoch 72/100
17520/17520 [==============================] - 23s 1ms/step - loss: 16.5973 - acc: 0.2560 - mae: 2.0097
Epoch 73/100
17520/17520 [==============================] - 22s 1ms/step - loss: 14.6110 - acc: 0.2633 - mae: 1.8807
Epoch 74/100
17520/17520 [==============================] - 22s 1ms/step - loss: 13.9312 - acc: 0.2679 - mae: 1.8342
Epoch 75/100
17520/17520 [==============================] - 25s 1ms/step - loss: 13.3651 - acc: 0.2667 - mae: 1.8299
Epoch 76/100
17520/17520 [==============================] - 23s 1ms/step - loss: 17.9693 - acc: 0.2511 - mae: 2.0683
Epoch 77/100
17520/17520 [==============================] - 21s 1ms/step - loss: 24.2583 - acc: 0.2535 - mae: 2.3028
Epoch 78/100
17520/17520 [==============================] - 21s 1ms/step - lo